import test from 'node:test';
import assert from 'node:assert/strict';
import {Forge,fixtures} from './engine.mjs';
const {builder,reviewer,client}=fixtures;
const specification={inputs:'text',outputs:'summary',dependencies:[],permissions:['memory.read'],acceptanceTests:['Returns summary'],rollback:'Remove simulated entry',budget:{maxAttempts:2,units:3}};
function setup(){const f=new Forge();let p=f.create(builder,{projectId:'demo-a',title:'Sample skill'});const go=(action,actor=builder,extra={})=>p=f.transition(actor,p.id,{action,revision:p.revision,...extra});return {f,go,get p(){return p;}};}
function review(s){s.go('specify',builder,{specification});s.go('build');s.go('test');s.go('result',builder,{outcome:'pass'});}
test('complete simulated lifecycle preserves queued job and never production-registers',()=>{const s=setup();review(s);s.go('approve_staging',reviewer);s.go('verify_staging');s.go('approve_promotion',reviewer);s.go('register');assert.equal(s.p.state,'registered');assert.equal(s.p.job.state,'queued');assert.equal(s.p.productionRegistered,false);s.go('revoke');s.go('rollback');assert.equal(s.p.state,'rolled_back');assert.equal(s.p.audit.at(-1).previous,s.p.audit.at(-2).digest);});
test('client cannot mutate or see another project or review evidence',()=>{const s=setup();review(s);assert.throws(()=>s.go('approve_staging',client),/Developer/);const view=s.f.list(client)[0];assert.equal(view.specification,undefined);assert.equal(view.audit,undefined);const other=s.f.create(builder,{projectId:'demo-b',title:'Other'});assert.throws(()=>s.f.get(client,other.id),/not found/);assert.equal(s.f.list(client).length,1);});
test('owner cannot approve, skip gates, or inject receipts',()=>{const s=setup();assert.throws(()=>s.go('register'),/promotion/);review(s);assert.throws(()=>s.go('approve_staging'),/Independent/);assert.throws(()=>s.go('approve_promotion',reviewer,{receipts:[{passed:true}]}),/Staging verification/);});
test('stale revisions and receipts rejected',()=>{const s=setup();review(s);assert.throws(()=>s.f.transition(reviewer,s.p.id,{action:'approve_staging',revision:0}),/Stale revision/);s.f.now=()=>Date.now()+61000;assert.throws(()=>s.go('approve_staging',reviewer),/fresh/);});
test('failed tests block approvals and retries are bounded',()=>{const s=setup();s.go('specify',builder,{specification});for(let i=0;i<2;i++){s.go('build');s.go('test');s.go('result',builder,{outcome:'fail'});assert.throws(()=>s.go('approve_staging',reviewer),/Passing tests/);}assert.throws(()=>s.go('build'),/budget exhausted/);});
test('exhausted resource budget cannot retry',()=>{const s=setup();s.go('specify',builder,{specification});s.go('build');s.go('test');s.go('result',builder,{outcome:'exhausted'});assert.equal(s.p.state,'failed');assert.throws(()=>s.go('build'),/budget exhausted/);});
test('policy modification permission denied and frozen spec cannot change',()=>{const s=setup();assert.throws(()=>s.go('specify',builder,{specification:{...specification,permissions:['policy.write']}}),/unsafe/);s.go('specify',builder,{specification});assert.throws(()=>s.go('specify',builder,{specification}),/frozen/);});
test('stale and unavailable worker block staging and regressions revoke',()=>{const s=setup();review(s);s.go('approve_staging',reviewer);for(const state of [{available:false,fresh:true},{available:true,fresh:false}]){s.f.workerScenario(builder,state);assert.throws(()=>s.go('verify_staging'),/unavailable|stale/);}s.f.workerScenario(builder,{available:true,fresh:true});s.go('verify_staging');s.go('approve_promotion',reviewer);s.go('register');s.f.workerScenario(builder,{available:false,fresh:false});assert.equal(s.f.get(builder,s.p.id).state,'revoked');assert.equal(s.f.audit.at(-1).action,'simulated_health_revocation');});
test('promotion cannot use expired staging evidence',()=>{const s=setup();review(s);s.go('approve_staging',reviewer);s.go('verify_staging');s.go('approve_promotion',reviewer);s.f.now=()=>Date.now()+61000;assert.throws(()=>s.go('register'),/Fresh staging/);});
test('rejection terminal and returned state cannot mutate server',()=>{const s=setup();review(s);s.p.specification.permissions.push('policy.write');assert.deepEqual(s.f.get(builder,s.p.id).specification.permissions,['memory.read']);s.go('reject',reviewer);assert.throws(()=>s.go('build'),/Cannot build/);});
